#	$NetBSD: Makefile,v 1.5 1995/02/25 09:02:37 cgd Exp $
#	$OpenBSD: Makefile,v 1.4 2005/11/24 20:49:18 deraadt Exp $

include ../config.mk

LIB=	libl.a
WANTLINT=
SRCS=	../lex/libmain.c ../lex/libyywrap.c
NOPIC=

include ../lib.mk
